/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountInfo: typeof import('./src/components/settings/components/AccountPage/AccountInfo.vue')['default']
    AccountSetting: typeof import('./src/components/user/AccountSetting.vue')['default']
    AsyncImage: typeof import('./src/components/common/AsyncImage.vue')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    DocsIndexView: typeof import('./src/components/docs/DocsIndexView.vue')['default']
    DocsItemCard: typeof import('./src/components/docs/DocsItemCard.vue')['default']
    DocsPage: typeof import('./src/components/docs/DocsPage.vue')['default']
    FestivalGear: typeof import('./src/components/settings/components/FestivalGear.vue')['default']
    ItemList: typeof import('./src/components/docs/ItemList.vue')['default']
    LoginDialog: typeof import('./src/components/user/LoginDialog.vue')['default']
    LoginPage: typeof import('./src/components/user/LoginPage.vue')['default']
    MarkdownRenderer: typeof import('./src/components/docs/MarkdownRenderer.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NoticeComponent: typeof import('./src/components/notice/NoticeComponent.vue')['default']
    NoticeItemCard: typeof import('./src/components/notice/components/NoticeItemCard.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SettingAccountPage: typeof import('./src/components/settings/components/SettingAccountPage.vue')['default']
    SettingDefaultPage: typeof import('./src/components/settings/components/SettingDefaultPage.vue')['default']
    SettingDialog: typeof import('./src/components/settings/SettingDialog.vue')['default']
    SettingLanguagePage: typeof import('./src/components/settings/components/SettingLanguagePage.vue')['default']
    SettingPage: typeof import('./src/components/settings/SettingPage.vue')['default']
    SettingTestPage: typeof import('./src/components/settings/components/SettingTestPage.vue')['default']
    SettingThemePage: typeof import('./src/components/settings/components/SettingThemePage.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
    WikiRepos: typeof import('./src/components/docs/WikiRepos.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
