name: Vue CI Pipeline

on:
  #  push:
  #    branches: [ dev ]  # 日常开发在 dev 分支
  pull_request:
    branches: [ main,dev ] # 只允许向 main,dev 发起 PR
    types: [ opened, synchronize, reopened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用指定版本的 Node.js

      - name: 确保 Corepack 是最新的
        run: npm install -g corepack@latest

      - name: Enable Corepack (for pnpm)
        run: corepack enable

      - name: Set registry to npmmirror（临时切换）
        run: pnpm config set registry https://registry.npmmirror.com

      - name: 安装依赖
        run: pnpm ci

      - name: 运行 Linter
        run: pnpm run lint

      - name: Type check with vue-tsc
        run: npx vue-tsc --noEmit  # 添加类型检查步骤

      - name: Build Vue.js project
        env:
          # VITE_BASE_PATH: '/cc.wiki.project.v4.web2/'
          VITE_BASE_PATH: '/'
        run: pnpm run build